# Generated by Django 2.0.2 on 2018-04-10 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trudy_api', '0003_auto_20180409_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
