# Generated by Django 2.0.2 on 2018-04-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trudy_api', '0005_child_tweets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='twitter_token',
            new_name='oauth_secret',
        ),
        migrations.AddField(
            model_name='child',
            name='oauth_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
