# Generated by Django 2.0.2 on 2018-04-14 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trudy_api', '0006_auto_20180415_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to=settings.AUTH_USER_MODEL),
        ),
    ]
